/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package primitive.types;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {

    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();

        // * a long has a 0 for default value
        assertEquals(0L, classUnderTest.beach);
        // * a boolean has a false default value
        assertFalse(classUnderTest.trueOrFalse);
        // * a int has a 0 value
        assertEquals(0, classUnderTest.eresting);
        // * a float has a default value of 0.0
        assertEquals(0f, classUnderTest.aison, 0);
        assertEquals(0, classUnderTest.aison, 0);
        assertEquals(0.0, classUnderTest.aison, 0);
        assertEquals(-0.0, classUnderTest.aison, 0);
        // * a char has a 0 for default value (decimal value 0)
        assertEquals(0, classUnderTest.dassault);
        assertEquals(classUnderTest.eresting, classUnderTest.dassault);
        assertNotEquals('0', classUnderTest.dassault);
        // * a short has a 0 for default value 
        assertEquals(0, classUnderTest.deBain);
        // * a double has a 0 for default value
        assertEquals(0D, classUnderTest.dribble, 0);
        assertEquals(0, classUnderTest.dribble, 0);
        assertEquals(0.0, classUnderTest.dribble, 0);
        assertEquals(-0.0, classUnderTest.dribble, 0);
        // * a byte has a 0 for default value
        assertEquals(0, classUnderTest.octet);


    }
}
