/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package primitive.types;

public class App {



    long beach;
    int eresting;
    char dassault;
    byte octet;
    double dribble;
    boolean trueOrFalse;
    float aison;
    short deBain;

    public App() {}

    public static void main(String[] args) {
    }
}
